application: slackernews
admin_console_password: ENC[AES256_GCM,data:UnfOdxqWOyz0hTZouU6NXKqdLpcc/FFbfUiYtmoPuTlFqD1GCRf+aQ==,iv:9zG5lAi3Gvz76rz1WkjbFzwVfH7nOGdPUyox7wcKa3I=,tag:6xNw+VuqVPah0hXFK4PYug==,type:str]
instance_type: m6i.xlarge
volume_size: 50
source_ami: ami-0a8aed1ef66d8d061
aws:
    access_key_id: ENC[AES256_GCM,data:de2r2d1dMN/3cZKKwOTgUCqAfNM=,iv:+PFlw3Bdxy5d0q5FWWZU6T3tkK5/LbodJF4ETjhPm+g=,tag:17OUdoQI5OFPBlyb36u01Q==,type:str]
    secret_access_key: ENC[AES256_GCM,data:mXtRR6X0Q9h0v79MfvmyT8TVdi4CNAuAeb0aJ/3LWhGhzybjYVBinQ==,iv:gYqvmq29Xu6FtmASoZS6w+S7qnbQucg98hAx4rx7DaE=,tag:nBpWGQjbv++aaplQuPARtQ==,type:str]
    region: us-west-2
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-28T18:28:11Z"
    mac: ENC[AES256_GCM,data:bGieVD1CR6N5vX6uQLTAR5EPZeW7Sjkvsq6OqB3+4HzBmI0nOfRvkKcjl+s7ZIK/ZNwnESQdAfXsCfjD/VjAH+UpuWvW93w5OJP6CrezIAWmO1s5INLF72Lg4tn9yARVz75kjnglk3GBNEF2MFcO/Z/c20JLuapmglGa6Sv1ZQ0=,iv:pHErOxyeeNb9lTop5yDpfC4jMNabV3LdVTqpJSw+QMM=,tag:SndWOJg88bKfQuHhnX4pcA==,type:str]
    pgp:
        - created_at: "2023-11-28T15:58:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdA0E+JrbUKVtpW2zOQoYcuJWvxbhRUBkD+/DdAwnQp204w
            vfVoSNlFUkxV2cinCajI3U7nAWLxLL/31/riExOCi0Kuux8WIpKtT025vE/reJSB
            1GYBCQIQN5hHFfDz/CQnGl0K/Nsm5rA6JE9GYJ6ZGnkUz1US2AxhsH9tuDH4Z/vo
            VpSgTwMze90qteu3CkVOcyoitkNytz/0FKMOViTUa04mBySR+E8aOOMisf9ptfYi
            1joFsroK7Kc=
            =IUeh
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: access_key|password
    version: 3.8.1
