application: slackernews-mackerel
default_password: ENC[AES256_GCM,data:IwPV9XWRTAEk,iv:P1gwcHZojmTSTYr+kEC/U1ls3+Duec545jrn+s0L7oY=,tag:l21vQDcMYzP9TaFAN7RATg==,type:str]
instance_type: m6i.xlarge
volume_size: 100
# ubuntu 22.04 LTS server ISO
source_iso: https://releases.ubuntu.com/releases/22.04/ubuntu-22.04.5-live-server-amd64.iso
source_iso_checksum: file:https://releases.ubuntu.com/22.04/SHA256SUMS
# us-west-2
source_ami: ami-0c0f84ffda87399e6
# us-east-1
# source_ami: ami-0f890494e52693975
replicated:
    api_token: ENC[AES256_GCM,data:k4WOoqRah2INtEoqgajKOu/FIABh9k8NBXHaN26LXV3L4cmqKLC0MlgpQI4n1kTUHoW9PwQwAOnTEJpBUHv+rg==,iv:oYYjGtfL3b5jNiyJjReVJOkkFRBZxwjQa8I6XEP7vKs=,tag:4Bk6/EMQg+Y77KjYrEPLLA==,type:str]
# replicated - for the development work
aws:
    # Personal
    access_key_id: ENC[AES256_GCM,data:b/PB0QTSfwV5jFjO5SkT/zSuR5w=,iv:cuhazc0ypsXB3kR4kIbWBr+TGa9MOF/0uNJYORRd+h4=,tag:pNbLI/yDs9tNm+LEdTpjiw==,type:str]
    secret_access_key: ENC[AES256_GCM,data:HwZgDwWkZJDAetsvfE2pIX9KhIz1GQUCdFJcDwf42HY4iWKmeYqNuw==,iv:y1SxQb+PDTDfepv0p1unnUKRJg5Ubx4d+cBy134tePk=,tag:+u0NUD1aVGnhhh82tYs80Q==,type:str]
    regions:
        - eu-central-1
        - us-west-1
        - ap-south-1
        - eu-north-1
        - ap-northeast-1
        - ca-central-1
        - eu-west-1
        - sa-east-1
        - us-east-1
        - ap-southeast-1
        - us-west-2
        - eu-west-2
        - ap-northeast-2
        - us-east-2
        - ap-southeast-2
        - eu-west-3
        - ap-northeast-3
# homelab
vsphere:
    server: vcenter.lab.shortrib.net
    username: terraform@shortrib.local
    password: ENC[AES256_GCM,data:sofdMhACL2aH9uexTOdqDGle/A==,iv:i9fxZJdY1gxfkw7Ub5VutsZx+CTWeklKOPo5TZlMyG4=,tag:EQFln2lpTOVWLKPPiVahfg==,type:str]
    datacenter: garage
    cluster: homelab
    host: rye.lab.shortrib.net
    resource_pool: homelab/Resources/clusters
    network: management-pg
    datastore: vsanDatastore
ssh:
    private_key_file: /home/crdant/.ssh/id_ed25519.pub
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-31T00:33:53Z"
    mac: ENC[AES256_GCM,data:QRNKWwqIjWi2F0BJVH2iE+Qc3fQa4M7VpSC2u0NfGvj3coXvbwCx4KavkM5oL9MO1pzgBlxXQlXKALJHOp8lW/vxJEZLF8CmYUpR3bKg3HwoToyvQZhy4Q1HaHGx4abFbbegnsRaPuJiJOKHUX3JugITLrFagS9+ty6U9pZCpoI=,iv:PRbXL7SmKF9b3nmQFG3/jez9z4LxIdLdVADDlwyxuy0=,tag:6HfshRzw/MddQue00Uwlbw==,type:str]
    pgp:
        - created_at: "2023-12-07T20:18:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdA835NMsL4VZjKW3H+4z9CbXcMY48vWqe6bmn/2WeM5z0w
            krkNWua6eLQcCz4CvTxhWKE2UoguvywW7ZZpUN7hvTX+Cu0BckjvXbRgA0lNCdFa
            1GgBCQIQanIB0MPkGw/M1yvbgff0bc0Bs1/9mpFAl13/DMzYU4b7B/mixWjpiLE3
            XE0pp4rVDIBIEUdy/i6e/QnwG+IjxPc/maDVug/QBqUNPpiqb9DOJ9qXRMunNHc0
            wXLJMlssVth3Cg==
            =/kuy
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: access_key|password|api_token
    version: 3.8.1
