application: slackernews-mackerel
admin_console_password: ENC[AES256_GCM,data:HWC5rc44f2FlAz0LRd8AgIPxixmzIDys06SaXFSzdoST/2vs4XL4tA==,iv:nHETvD7nIa7BDn3ABFBu8U4Pvp7RW7T10Mzzp4agG7I=,tag:v2a4QsdhQBVuN7Wge+cczQ==,type:str]
instance_type: m6i.xlarge
volume_size: 50
# us-west-2
source_ami: ami-0c0f84ffda87399e6
# us-east-1
# source_ami: ami-0f890494e52693975
replicated:
    api_token: ENC[AES256_GCM,data:od3e5Plxay/r+cZwt3DeLxqH4D02HKB763mnqEqgN0RG80oE/ttY7lv6QuZxs4gUkf+OJnW9IH3g+WaUXpaJgA==,iv:jiUa88GVQJzljzkamF3UxDBBhhnqWzl/QSdhXkwhefw=,tag:Fy9znvc28VY6aCzfJoh7tA==,type:str]
# replicated - for the development work
aws:
    access_key_id: ENC[AES256_GCM,data:jXhut2LzBsZZye28Q4EIGJSTFrY=,iv:I+DpRLccJNqWojeFqjjSkCA8y43E0EbkIoL6zt24eL4=,tag:ocx9KvrXk/tm0Gisk1BVgA==,type:str]
    secret_access_key: ENC[AES256_GCM,data:+eSNfbaX1RIKLwhIgPrWTMjvWFfbWEAVOdZo7vK0UfhQa1N0M2GcgQ==,iv:M74vlIlWV3mhV1S+2H54jQXvNmjPrGAc8lQw+vpDaYY=,tag:pf9cEK5xdiLhrGjXUwy/5w==,type:str]
    regions:
        - eu-central-1
        - us-west-1
        - ap-south-1
        - eu-north-1
        - ap-northeast-1
        - ca-central-1
        - eu-west-1
        - sa-east-1
        - us-east-1
        - ap-southeast-1
        - us-west-2
        - eu-west-2
        - ap-northeast-2
        - us-east-2
        - ap-southeast-2
        - eu-west-3
        - ap-northeast-3
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-30T15:52:48Z"
    mac: ENC[AES256_GCM,data:/Xvc+GzfAzB7sx7LsOvM6OpNZcOyEcd+HF/eXcUoVp1uXcZ/YikORh+IsKYEq1gZES7l14UE13GjhK1ALRiKBCMCAGWEwMCiSa4BsrfH3SzUFIROJAQGBAYI3yAS/Yd2ryKMOdnDySb8BwgKMM9XYk3l4Ypu7x0PaZksUb+SKtk=,iv:XUQ2/t6bpcAN6yQQXFodMvl+6VC6HhBru9bC9YYGIxg=,tag:4lscRy1Mh5S3JmwSot88nw==,type:str]
    pgp:
        - created_at: "2023-12-07T20:18:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdA835NMsL4VZjKW3H+4z9CbXcMY48vWqe6bmn/2WeM5z0w
            krkNWua6eLQcCz4CvTxhWKE2UoguvywW7ZZpUN7hvTX+Cu0BckjvXbRgA0lNCdFa
            1GgBCQIQanIB0MPkGw/M1yvbgff0bc0Bs1/9mpFAl13/DMzYU4b7B/mixWjpiLE3
            XE0pp4rVDIBIEUdy/i6e/QnwG+IjxPc/maDVug/QBqUNPpiqb9DOJ9qXRMunNHc0
            wXLJMlssVth3Cg==
            =/kuy
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: access_key|password|api_token
    version: 3.8.1
